Ensure that the WiFi reconnects if it drops out
michaelkamprath/diy-air-quality-monitor pull request #7
Opened 2022-05-01 00:38 UTC by trailtacos

This change ensures that the main loop will attempt a wifi reconnection,
once every 60 seconds (by default) if it disconnects. Previously, if you
didn't have the JSON upload feature enabled it would never reconnect to
an AP that it got disconnected from.

 Please enter the commit message for your changes. Lines starting

2022-05-03 17:27 UTC, michaelkamprath requested changes

2022-05-03 17:27 UTC, michaelkamprath commented on src/Application.cpp
> +    return;
So this skips the rest of the loop even if the wifi reconnects. Should the `return` only be called if the wifi fails to reconnect?

2022-05-04 01:37 UTC, trailtacos commented on src/Application.cpp
> +    return;
Yes, its the `reconnect()` function doesn't actually reconnect - it just initiates a background reconnect (at least that is my reading), so I believe its better to `return`, and check the status the next loop (and upload if there is a pending upload).

However - I haven't specificially tested this (i.e. looking at return values etc) if the reconnect fails, I might be able to confirm/deny that this weekend

2022-05-04 02:28 UTC, michaelkamprath commented on src/Application.cpp
> +    return;
works for me

2022-05-04 02:28 UTC, michaelkamprath approved these changes

2022-05-04 02:28 UTC, merged